create table users
(
    id       bigint generated by default as identity
        primary key,
    password varchar(255) not null,
    username varchar(255) not null
        constraint ukr43af9ap4edm43mmtq01oddj6
            unique
);

alter table users
    owner to yeyokp_rpg;

